In [44]:
# IMPORTS NEEDED FOR CODE TO RUN
import csv
import numpy as np
import pandas as pd
import regex as re

In [45]:
"""
    Function for stripping column names as well as data values of redundant white spaces.
"""
def strip_df_whitespaces(dataframe):
    # Strip column names of whitepaces
    column_names = [column.strip() for column in dataframe.columns]
    dataframe.columns = column_names

    # Strip datavalues of whitespaces
    dataframe = dataframe.map(lambda x: x.strip() if isinstance(x, str) else x)

    # Return result
    return dataframe

In [46]:
# Load in the uncleaned tabloid data
uncleaned_coverage_data = open("..\data\own_coverage_uncleaned.txt", encoding='UTF-8').read()

print(uncleaned_coverage_data)

| Category | # | Description | Implementation-Status | MAS-Status |
|----------|----------|----------|----------|----------|
| STORAGE |  |  |  |  |
|  | [0001](https://mas.owasp.org/MASWE/MASVS-STORAGE/MASWE-0001/) | Insertion of Sensitive Data into Logs |1| Beta |
|  | [0002](https://mas.owasp.org/MASWE/MASVS-STORAGE/MASWE-0002/) | Sensitive Data Stored With Insufficient Access Restrictions in Internal Locations |1| Placeholder |
|  | [0003](https://mas.owasp.org/MASWE/MASVS-STORAGE/MASWE-0003/) | Backup Unencrypted |1| Placeholder |
|  | [0004](https://mas.owasp.org/MASWE/MASVS-STORAGE/MASWE-0004/) | Sensitive Data Not Excluded From Backup |1| Beta |
|  | [0006](https://mas.owasp.org/MASWE/MASVS-STORAGE/MASWE-0006/) | Sensitive Data Stored Unencrypted in Private Storage Locations |1| Beta |
|  | [0007](https://mas.owasp.org/MASWE/MASVS-STORAGE/MASWE-0007/) | Sensitive Data Stored Unencrypted in Shared Storage Requiring No User Interaction |1| Beta |
| CRYPTO |  |  |  |  |
|  | [0009](https://mas.owasp.org/MASWE/MASVS-CRYPTO/MASWE-0009/) | Improper Cryptographic Key Generation |1| Beta |
|  | [0010](https://mas.owasp.org/MASWE/MASVS-CRYPTO/MASWE-0010/) | Improper Cryptographic Key Derivation |1| Placeholder |
|  | [0011](https://mas.owasp.org/MASWE/MASVS-CRYPTO/MASWE-0011/) | Cryptographic Key Rotation Not Implemented |1| Placeholder |
|  | [0012](https://mas.owasp.org/MASWE/MASVS-CRYPTO/MASWE-0012/) | Insecure or Wrong Usage of Cryptographic Key |1| Placeholder |
|  | [0013](https://mas.owasp.org/MASWE/MASVS-CRYPTO/MASWE-0013/) | Hardcoded Cryptographic Keys in Use |0| DEPRECATED |
|  | [0014](https://mas.owasp.org/MASWE/MASVS-CRYPTO/MASWE-0014/) | Cryptographic Keys Not Properly Protected at Rest |1| Beta |
|  | [0015](https://mas.owasp.org/MASWE/MASVS-CRYPTO/MASWE-0015/) | Deprecated Android KeyStore Implementations |1| Placeholder |
|  | [0016](https://mas.owasp.org/MASWE/MASVS-CRYPTO/MASWE-0016/) | Unsafe Handling of Imported Cryptographic Keys |1| Placeholder |
|  | [0017](https://mas.owasp.org/MASWE/MASVS-CRYPTO/MASWE-0017/) | Cryptographic Keys Not Properly Protected on Export |1| Placeholder |
|  | [0018](https://mas.owasp.org/MASWE/MASVS-CRYPTO/MASWE-0018/) | Cryptographic Keys Access Not Restricted |1| Placeholder |
|  | [0019](https://mas.owasp.org/MASWE/MASVS-CRYPTO/MASWE-0019/) | Risky Cryptography Implementations |1| Normal |
|  | [0020](https://mas.owasp.org/MASWE/MASVS-CRYPTO/MASWE-0020/) | Improper Encryption |1| Beta |
|  | [0021](https://mas.owasp.org/MASWE/MASVS-CRYPTO/MASWE-0021/) | Improper Hashing |1| Placeholder |
|  | [0022](https://mas.owasp.org/MASWE/MASVS-CRYPTO/MASWE-0022/) | Predictable Initialization Vectors (IVs) |1| Placeholder |
|  | [0023](https://mas.owasp.org/MASWE/MASVS-CRYPTO/MASWE-0023/) | Risky Padding |1| Beta |
|  | [0024](https://mas.owasp.org/MASWE/MASVS-CRYPTO/MASWE-0024/) | Improper Use of Message Authentication Code (MAC) |1| Placeholder |
|  | [0025](https://mas.owasp.org/MASWE/MASVS-CRYPTO/MASWE-0025/) | Improper Generation of Cryptographic Signatures |1| Placeholder |
|  | [0026](https://mas.owasp.org/MASWE/MASVS-CRYPTO/MASWE-0026/) | Improper Verification of Cryptographic Signature |1| Placeholder |
|  | [0027](https://mas.owasp.org/MASWE/MASVS-CRYPTO/MASWE-0027/) | Improper Random Number Generation |1| Beta |
| AUTH |  |  |  |  |
|  | [0005](https://mas.owasp.org/MASWE/MASVS-AUTH/MASWE-0005/) | API Keys Hardcoded in the App Package |0| Beta |
|  | [0028](https://mas.owasp.org/MASWE/MASVS-AUTH/MASWE-0028/) | MFA Implementation Best Practices Not Followed |0| Placeholder |
|  | [0029](https://mas.owasp.org/MASWE/MASVS-AUTH/MASWE-0029/) | Step-Up Authentication Not Implemented After Login |0| Placeholder |
|  | [0030](https://mas.owasp.org/MASWE/MASVS-AUTH/MASWE-0030/) | Re-Authenticates Not Triggered On Contextual State Changes |0| Placeholder |
|  | [0031](https://mas.owasp.org/MASWE/MASVS-AUTH/MASWE-0031/) | Insecure use of Android Protected Confirmation |0| Placeholder |
|  | [0032](https://mas.owasp.org/MASWE/MASVS-AUTH/MASWE-0032/) | Platform-provided Authentication APIs Not Used |0| Placeholder |
|  | [0033](https://mas.owasp.org/MASWE/MASVS-AUTH/MASWE-0033/) | Authentication or Authorization Protocol Security Best Practices Not Followed |0| Placeholder |
|  | [0034](https://mas.owasp.org/MASWE/MASVS-AUTH/MASWE-0034/) | Insecure Implementation of Confirm Credentials |0| DEPRECATED |
|  | [0035](https://mas.owasp.org/MASWE/MASVS-AUTH/MASWE-0035/) | Passwordless Authentication Not Implemented |0| Placeholder |
|  | [0036](https://mas.owasp.org/MASWE/MASVS-AUTH/MASWE-0036/) | Authentication Material Stored Unencrypted on the Device |0| Placeholder |
|  | [0037](https://mas.owasp.org/MASWE/MASVS-AUTH/MASWE-0037/) | Authentication Material Sent over Insecure Connections |0| Placeholder |
|  | [0038](https://mas.owasp.org/MASWE/MASVS-AUTH/MASWE-0038/) | Authentication Tokens Not Validated |0| Placeholder |
|  | [0039](https://mas.owasp.org/MASWE/MASVS-AUTH/MASWE-0039/) | Shared Web Credentials and Website-association Not Implemented |0| Placeholder |
|  | [0040](https://mas.owasp.org/MASWE/MASVS-AUTH/MASWE-0040/) | Insecure Authentication in WebViews |0| Placeholder |
|  | [0041](https://mas.owasp.org/MASWE/MASVS-AUTH/MASWE-0041/) | Authentication Enforced Only Locally Instead of on the Server-side |0| Placeholder |
|  | [0042](https://mas.owasp.org/MASWE/MASVS-AUTH/MASWE-0042/) | Authorization Enforced Only Locally Instead of on the Server-side |0| Placeholder |
|  | [0043](https://mas.owasp.org/MASWE/MASVS-AUTH/MASWE-0043/) | App Custom PIN Not Bound to Platform KeyStore |0| Placeholder |
|  | [0044](https://mas.owasp.org/MASWE/MASVS-AUTH/MASWE-0044/) | Biometric Authentication Can Be Bypassed |0| Placeholder |
|  | [0045](https://mas.owasp.org/MASWE/MASVS-AUTH/MASWE-0045/) | Fallback to Non-biometric Credentials Allowed for Sensitive Transactions |0| Placeholder |
|  | [0046](https://mas.owasp.org/MASWE/MASVS-AUTH/MASWE-0046/) | Crypto Keys Not Invalidated on New Biometric Enrollment |0| Placeholder |
| NETWORK |  |  |  |  |
|  | [0047](https://mas.owasp.org/MASWE/MASVS-NETWORK/MASWE-0047/) | Insecure Identity Pinning |0| Beta |
|  | [0048](https://mas.owasp.org/MASWE/MASVS-NETWORK/MASWE-0048/) | Insecure Machine-to-Machine Communication |0| Placeholder |
|  | [0049](https://mas.owasp.org/MASWE/MASVS-NETWORK/MASWE-0049/) | Proven Networking APIs Not used |0| Beta |
|  | [0050](https://mas.owasp.org/MASWE/MASVS-NETWORK/MASWE-0050/) | Cleartext Traffic |0| Beta |
|  | [0051](https://mas.owasp.org/MASWE/MASVS-NETWORK/MASWE-0051/) | Unprotected Open Ports |0| Beta |
|  | [0052](https://mas.owasp.org/MASWE/MASVS-NETWORK/MASWE-0052/) | Insecure Certificate Validation |0| Beta |
| PLATFORM |  |  |  |  |
|  | [0053](https://mas.owasp.org/MASWE/MASVS-PLATFORM/MASWE-0053/) | Sensitive Data Leaked via the User Interface |1| Placeholder |
|  | [0054](https://mas.owasp.org/MASWE/MASVS-PLATFORM/MASWE-0054/) | Sensitive Data Leaked via Notifications |0| Placeholder |
|  | [0055](https://mas.owasp.org/MASWE/MASVS-PLATFORM/MASWE-0055/) | Sensitive Data Leaked via Screenshots |1| Placeholder |
|  | [0056](https://mas.owasp.org/MASWE/MASVS-PLATFORM/MASWE-0056/) | Tapjacking Attacks |0| Placeholder |
|  | [0057](https://mas.owasp.org/MASWE/MASVS-PLATFORM/MASWE-0057/) | StrandHogg Attack / Task Affinity Vulnerability |0| Placeholder |
|  | [0058](https://mas.owasp.org/MASWE/MASVS-PLATFORM/MASWE-0058/) | Insecure Deep Links |0| Placeholder |
|  | [0059](https://mas.owasp.org/MASWE/MASVS-PLATFORM/MASWE-0059/) | Use Of Unauthenticated Platform IPC |0| Placeholder |
|  | [0060](https://mas.owasp.org/MASWE/MASVS-PLATFORM/MASWE-0060/) | Insecure Use of UIActivity |0| Placeholder |
|  | [0061](https://mas.owasp.org/MASWE/MASVS-PLATFORM/MASWE-0061/) | Insecure Use of App Extensions |0| Placeholder |
|  | [0062](https://mas.owasp.org/MASWE/MASVS-PLATFORM/MASWE-0062/) | Insecure Services |0| Placeholder |
|  | [0063](https://mas.owasp.org/MASWE/MASVS-PLATFORM/MASWE-0063/) | Insecure Broadcast Receivers |0| Placeholder |
|  | [0064](https://mas.owasp.org/MASWE/MASVS-PLATFORM/MASWE-0064/) | Insecure Content Providers |1| Placeholder |
|  | [0065](https://mas.owasp.org/MASWE/MASVS-PLATFORM/MASWE-0065/) | Sensitive Data Permanently Shared with Other Apps |0| Placeholder |
|  | [0066](https://mas.owasp.org/MASWE/MASVS-PLATFORM/MASWE-0066/) | Insecure Intents |0| Placeholder |
|  | [0067](https://mas.owasp.org/MASWE/MASVS-PLATFORM/MASWE-0067/) | Debuggable Flag Not Disabled |1| Beta |
|  | [0068](https://mas.owasp.org/MASWE/MASVS-PLATFORM/MASWE-0068/) | JavaScript Bridges in WebViews |0| Placeholder |
|  | [0069](https://mas.owasp.org/MASWE/MASVS-PLATFORM/MASWE-0069/) | WebViews Allows Access to Local Resources |0| Placeholder |
|  | [0070](https://mas.owasp.org/MASWE/MASVS-PLATFORM/MASWE-0070/) | JavaScript Loaded from Untrusted Sources |0| Placeholder |
|  | [0071](https://mas.owasp.org/MASWE/MASVS-PLATFORM/MASWE-0071/) | WebViews Loading Content from Untrusted Sources |0| Placeholder |
|  | [0072](https://mas.owasp.org/MASWE/MASVS-PLATFORM/MASWE-0072/) | Universal XSS |0| Placeholder |
|  | [0073](https://mas.owasp.org/MASWE/MASVS-PLATFORM/MASWE-0073/) | Insecure WebResourceResponse Implementations |0| Placeholder |
|  | [0074](https://mas.owasp.org/MASWE/MASVS-PLATFORM/MASWE-0074/) | Web Content Debugging Enabled |0| Placeholder |
| CODE |  |  |  |  |
|  | [0075](https://mas.owasp.org/MASWE/MASVS-CODE/MASWE-0075/) | Enforced Updating Not Implemented |0| Placeholder |
|  | [0076](https://mas.owasp.org/MASWE/MASVS-CODE/MASWE-0076/) | Dependencies with Known Vulnerabilities |0| Beta |
|  | [0077](https://mas.owasp.org/MASWE/MASVS-CODE/MASWE-0077/) | Running on a recent Platform Version Not Ensured |0| Placeholder |
|  | [0078](https://mas.owasp.org/MASWE/MASVS-CODE/MASWE-0078/) | Latest Platform Version Not Targeted |0| Placeholder |
|  | [0079](https://mas.owasp.org/MASWE/MASVS-CODE/MASWE-0079/) | Unsafe Handling of Data from the Network |0| Placeholder |
|  | [0080](https://mas.owasp.org/MASWE/MASVS-CODE/MASWE-0080/) | Unsafe Handling of Data from Backups |0| Placeholder |
|  | [0081](https://mas.owasp.org/MASWE/MASVS-CODE/MASWE-0081/) | Unsafe Handling Of Data From External Interfaces |0| Placeholder |
|  | [0082](https://mas.owasp.org/MASWE/MASVS-CODE/MASWE-0082/) | Unsafe Handling of Data From Local Storage |0| Placeholder |
|  | [0083](https://mas.owasp.org/MASWE/MASVS-CODE/MASWE-0083/) | Unsafe Handling of Data From The User Interface |0| Placeholder |
|  | [0084](https://mas.owasp.org/MASWE/MASVS-CODE/MASWE-0084/) | Unsafe Handling of Data from IPC |0| Placeholder |
|  | [0085](https://mas.owasp.org/MASWE/MASVS-CODE/MASWE-0085/) | Unsafe Dynamic Code Loading |0| Placeholder |
|  | [0086](https://mas.owasp.org/MASWE/MASVS-CODE/MASWE-0086/) | SQL Injection |0| Placeholder |
|  | [0087](https://mas.owasp.org/MASWE/MASVS-CODE/MASWE-0087/) | Insecure Parsing and Escaping |0| Placeholder |
|  | [0088](https://mas.owasp.org/MASWE/MASVS-CODE/MASWE-0088/) | Insecure Object Deserialization |0| Placeholder |
|  | [0116](https://mas.owasp.org/MASWE/MASVS-CODE/MASWE-0116/) | Compiler Provided Security Features Not Used |0| Placeholder |
| RESILIENCE |  |  |  |  |
|  | [0008](https://mas.owasp.org/MASWE/MASVS-RESILIENCE/MASWE-0008/) | Missing Device Secure Lock Verification Implementation |0| Placeholder |
|  | [0089](https://mas.owasp.org/MASWE/MASVS-RESILIENCE/MASWE-0089/) | Code Obfuscation Not Implemented |0| Placeholder |
|  | [0090](https://mas.owasp.org/MASWE/MASVS-RESILIENCE/MASWE-0090/) | Resource Obfuscation Not Implemented |0| Placeholder |
|  | [0091](https://mas.owasp.org/MASWE/MASVS-RESILIENCE/MASWE-0091/) | Anti-Deobfuscation Techniques Not Implemented |0| Placeholder |
|  | [0092](https://mas.owasp.org/MASWE/MASVS-RESILIENCE/MASWE-0092/) | Static Analysis Tools Not Prevented |0| Placeholder |
|  | [0093](https://mas.owasp.org/MASWE/MASVS-RESILIENCE/MASWE-0093/) | Debugging Symbols Not Removed |0| Placeholder |
|  | [0094](https://mas.owasp.org/MASWE/MASVS-RESILIENCE/MASWE-0094/) | Non-Production Resources Not Removed |0| Placeholder |
|  | [0095](https://mas.owasp.org/MASWE/MASVS-RESILIENCE/MASWE-0095/) | Code That Disables Security Controls Not Removed |0| Placeholder |
|  | [0096](https://mas.owasp.org/MASWE/MASVS-RESILIENCE/MASWE-0096/) | Data Sent Unencrypted Over Encrypted Connections |0| Placeholder |
|  | [0097](https://mas.owasp.org/MASWE/MASVS-RESILIENCE/MASWE-0097/) | Root/Jailbreak Detection Not Implemented |0| Placeholder |
|  | [0098](https://mas.owasp.org/MASWE/MASVS-RESILIENCE/MASWE-0098/) | App Virtualization Environment Detection Not Implemented |0| Placeholder |
|  | [0099](https://mas.owasp.org/MASWE/MASVS-RESILIENCE/MASWE-0099/) | Emulator Detection Not Implemented |0| Placeholder |
|  | [0100](https://mas.owasp.org/MASWE/MASVS-RESILIENCE/MASWE-0100/) | Device Attestation Not Implemented |0| Placeholder |
|  | [0101](https://mas.owasp.org/MASWE/MASVS-RESILIENCE/MASWE-0101/) | Debugger Detection Not Implemented |0| Placeholder |
|  | [0102](https://mas.owasp.org/MASWE/MASVS-RESILIENCE/MASWE-0102/) | Dynamic Analysis Tools Detection Not Implemented |0| Placeholder |
|  | [0103](https://mas.owasp.org/MASWE/MASVS-RESILIENCE/MASWE-0103/) | RASP Techniques Not Implemented |0| Placeholder |
|  | [0104](https://mas.owasp.org/MASWE/MASVS-RESILIENCE/MASWE-0104/) | App Integrity Not Verified |0| Placeholder |
|  | [0105](https://mas.owasp.org/MASWE/MASVS-RESILIENCE/MASWE-0105/) | Integrity of App Resources Not Verified |0| Placeholder |
|  | [0106](https://mas.owasp.org/MASWE/MASVS-RESILIENCE/MASWE-0106/) | Official Store Verification Not Implemented |0| Placeholder |
|  | [0107](https://mas.owasp.org/MASWE/MASVS-RESILIENCE/MASWE-0107/) | Runtime Code Integrity Not Verified |0| Placeholder |
| PRIVACY |  |  |  |  |
|  | [0108](https://mas.owasp.org/MASWE/MASVS-PRIVACY/MASWE-0108/) | Sensitive Data in Network Traffic |0| Beta |
|  | [0109](https://mas.owasp.org/MASWE/MASVS-PRIVACY/MASWE-0109/) | Lack of Anonymization or Pseudonymisation Measures |0| Beta |
|  | [0110](https://mas.owasp.org/MASWE/MASVS-PRIVACY/MASWE-0110/) |  Use of Unique Identifiers for User Tracking |0| Beta |
|  | [0111](https://mas.owasp.org/MASWE/MASVS-PRIVACY/MASWE-0111/) | Inadequate Privacy Policy |0| Beta |
|  | [0112](https://mas.owasp.org/MASWE/MASVS-PRIVACY/MASWE-0112/) | Inadequate Data Collection Declarations |0| Beta |
|  | [0113](https://mas.owasp.org/MASWE/MASVS-PRIVACY/MASWE-0113/) | Lack of Proper Data Management Controls |0| Beta |
|  | [0114](https://mas.owasp.org/MASWE/MASVS-PRIVACY/MASWE-0114/) | Inadequate Data Visibility Controls |0| Beta |
|  | [0115](https://mas.owasp.org/MASWE/MASVS-PRIVACY/MASWE-0115/) | Inadequate or Ambiguous User Consent Mechanisms |0| Beta |
|  | [0117](https://mas.owasp.org/MASWE/MASVS-PRIVACY/MASWE-0117/) | Inadequate Permission Management |0| Beta |

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
C:\Users\Domi\AppData\Local\Temp\ipykernel_16984\304693285.py:2: SyntaxWarning: invalid escape sequence '\d'
  uncleaned_coverage_data = open("..\data\own_coverage_uncleaned.txt", encoding='UTF-8').read()

In [47]:
# Use regular expressions to reformat app names
# Regex pattern: replaces [AppName](https://github.com/anything) → AppName
uncleaned_coverage_data = re.sub(r"\[([^\]]+)\]\(https://mas.owasp\.org/[^\)]+\)", r"\1", uncleaned_coverage_data)
display(uncleaned_coverage_data)

'| Category | # | Description | Implementation-Status | MAS-Status |\n|----------|----------|----------|----------|----------|\n| STORAGE |  |  |  |  |\n|  | 0001 | Insertion of Sensitive Data into Logs |1| Beta |\n|  | 0002 | Sensitive Data Stored With Insufficient Access Restrictions in Internal Locations |1| Placeholder |\n|  | 0003 | Backup Unencrypted |1| Placeholder |\n|  | 0004 | Sensitive Data Not Excluded From Backup |1| Beta |\n|  | 0006 | Sensitive Data Stored Unencrypted in Private Storage Locations |1| Beta |\n|  | 0007 | Sensitive Data Stored Unencrypted in Shared Storage Requiring No User Interaction |1| Beta |\n| CRYPTO |  |  |  |  |\n|  | 0009 | Improper Cryptographic Key Generation |1| Beta |\n|  | 0010 | Improper Cryptographic Key Derivation |1| Placeholder |\n|  | 0011 | Cryptographic Key Rotation Not Implemented |1| Placeholder |\n|  | 0012 | Insecure or Wrong Usage of Cryptographic Key |1| Placeholder |\n|  | 0013 | Hardcoded Cryptographic Keys in Use |0| DEPRECATED |\n|  | 0014 | Cryptographic Keys Not Properly Protected at Rest |1| Beta |\n|  | 0015 | Deprecated Android KeyStore Implementations |1| Placeholder |\n|  | 0016 | Unsafe Handling of Imported Cryptographic Keys |1| Placeholder |\n|  | 0017 | Cryptographic Keys Not Properly Protected on Export |1| Placeholder |\n|  | 0018 | Cryptographic Keys Access Not Restricted |1| Placeholder |\n|  | 0019 | Risky Cryptography Implementations |1| Normal |\n|  | 0020 | Improper Encryption |1| Beta |\n|  | 0021 | Improper Hashing |1| Placeholder |\n|  | 0022 | Predictable Initialization Vectors (IVs) |1| Placeholder |\n|  | 0023 | Risky Padding |1| Beta |\n|  | 0024 | Improper Use of Message Authentication Code (MAC) |1| Placeholder |\n|  | 0025 | Improper Generation of Cryptographic Signatures |1| Placeholder |\n|  | 0026 | Improper Verification of Cryptographic Signature |1| Placeholder |\n|  | 0027 | Improper Random Number Generation |1| Beta |\n| AUTH |  |  |  |  |\n|  | 0005 | API Keys Hardcoded in the App Package |0| Beta |\n|  | 0028 | MFA Implementation Best Practices Not Followed |0| Placeholder |\n|  | 0029 | Step-Up Authentication Not Implemented After Login |0| Placeholder |\n|  | 0030 | Re-Authenticates Not Triggered On Contextual State Changes |0| Placeholder |\n|  | 0031 | Insecure use of Android Protected Confirmation |0| Placeholder |\n|  | 0032 | Platform-provided Authentication APIs Not Used |0| Placeholder |\n|  | 0033 | Authentication or Authorization Protocol Security Best Practices Not Followed |0| Placeholder |\n|  | 0034 | Insecure Implementation of Confirm Credentials |0| DEPRECATED |\n|  | 0035 | Passwordless Authentication Not Implemented |0| Placeholder |\n|  | 0036 | Authentication Material Stored Unencrypted on the Device |0| Placeholder |\n|  | 0037 | Authentication Material Sent over Insecure Connections |0| Placeholder |\n|  | 0038 | Authentication Tokens Not Validated |0| Placeholder |\n|  | 0039 | Shared Web Credentials and Website-association Not Implemented |0| Placeholder |\n|  | 0040 | Insecure Authentication in WebViews |0| Placeholder |\n|  | 0041 | Authentication Enforced Only Locally Instead of on the Server-side |0| Placeholder |\n|  | 0042 | Authorization Enforced Only Locally Instead of on the Server-side |0| Placeholder |\n|  | 0043 | App Custom PIN Not Bound to Platform KeyStore |0| Placeholder |\n|  | 0044 | Biometric Authentication Can Be Bypassed |0| Placeholder |\n|  | 0045 | Fallback to Non-biometric Credentials Allowed for Sensitive Transactions |0| Placeholder |\n|  | 0046 | Crypto Keys Not Invalidated on New Biometric Enrollment |0| Placeholder |\n| NETWORK |  |  |  |  |\n|  | 0047 | Insecure Identity Pinning |0| Beta |\n|  | 0048 | Insecure Machine-to-Machine Communication |0| Placeholder |\n|  | 0049 | Proven Networking APIs Not used |0| Beta |\n|  | 0050 | Cleartext Traffic |0| Beta |\n|  | 0051 | Unprotected Open Ports |0| Beta |\n|  | 0052 | Insecure Certificate Validation |0| Beta |\n| PLATFORM |  |  |  |  |\n|  | 0053 | Sensitive Data Leaked via the User Interface |1| Placeholder |\n|  | 0054 | Sensitive Data Leaked via Notifications |0| Placeholder |\n|  | 0055 | Sensitive Data Leaked via Screenshots |1| Placeholder |\n|  | 0056 | Tapjacking Attacks |0| Placeholder |\n|  | 0057 | StrandHogg Attack / Task Affinity Vulnerability |0| Placeholder |\n|  | 0058 | Insecure Deep Links |0| Placeholder |\n|  | 0059 | Use Of Unauthenticated Platform IPC |0| Placeholder |\n|  | 0060 | Insecure Use of UIActivity |0| Placeholder |\n|  | 0061 | Insecure Use of App Extensions |0| Placeholder |\n|  | 0062 | Insecure Services |0| Placeholder |\n|  | 0063 | Insecure Broadcast Receivers |0| Placeholder |\n|  | 0064 | Insecure Content Providers |1| Placeholder |\n|  | 0065 | Sensitive Data Permanently Shared with Other Apps |0| Placeholder |\n|  | 0066 | Insecure Intents |0| Placeholder |\n|  | 0067 | Debuggable Flag Not Disabled |1| Beta |\n|  | 0068 | JavaScript Bridges in WebViews |0| Placeholder |\n|  | 0069 | WebViews Allows Access to Local Resources |0| Placeholder |\n|  | 0070 | JavaScript Loaded from Untrusted Sources |0| Placeholder |\n|  | 0071 | WebViews Loading Content from Untrusted Sources |0| Placeholder |\n|  | 0072 | Universal XSS |0| Placeholder |\n|  | 0073 | Insecure WebResourceResponse Implementations |0| Placeholder |\n|  | 0074 | Web Content Debugging Enabled |0| Placeholder |\n| CODE |  |  |  |  |\n|  | 0075 | Enforced Updating Not Implemented |0| Placeholder |\n|  | 0076 | Dependencies with Known Vulnerabilities |0| Beta |\n|  | 0077 | Running on a recent Platform Version Not Ensured |0| Placeholder |\n|  | 0078 | Latest Platform Version Not Targeted |0| Placeholder |\n|  | 0079 | Unsafe Handling of Data from the Network |0| Placeholder |\n|  | 0080 | Unsafe Handling of Data from Backups |0| Placeholder |\n|  | 0081 | Unsafe Handling Of Data From External Interfaces |0| Placeholder |\n|  | 0082 | Unsafe Handling of Data From Local Storage |0| Placeholder |\n|  | 0083 | Unsafe Handling of Data From The User Interface |0| Placeholder |\n|  | 0084 | Unsafe Handling of Data from IPC |0| Placeholder |\n|  | 0085 | Unsafe Dynamic Code Loading |0| Placeholder |\n|  | 0086 | SQL Injection |0| Placeholder |\n|  | 0087 | Insecure Parsing and Escaping |0| Placeholder |\n|  | 0088 | Insecure Object Deserialization |0| Placeholder |\n|  | 0116 | Compiler Provided Security Features Not Used |0| Placeholder |\n| RESILIENCE |  |  |  |  |\n|  | 0008 | Missing Device Secure Lock Verification Implementation |0| Placeholder |\n|  | 0089 | Code Obfuscation Not Implemented |0| Placeholder |\n|  | 0090 | Resource Obfuscation Not Implemented |0| Placeholder |\n|  | 0091 | Anti-Deobfuscation Techniques Not Implemented |0| Placeholder |\n|  | 0092 | Static Analysis Tools Not Prevented |0| Placeholder |\n|  | 0093 | Debugging Symbols Not Removed |0| Placeholder |\n|  | 0094 | Non-Production Resources Not Removed |0| Placeholder |\n|  | 0095 | Code That Disables Security Controls Not Removed |0| Placeholder |\n|  | 0096 | Data Sent Unencrypted Over Encrypted Connections |0| Placeholder |\n|  | 0097 | Root/Jailbreak Detection Not Implemented |0| Placeholder |\n|  | 0098 | App Virtualization Environment Detection Not Implemented |0| Placeholder |\n|  | 0099 | Emulator Detection Not Implemented |0| Placeholder |\n|  | 0100 | Device Attestation Not Implemented |0| Placeholder |\n|  | 0101 | Debugger Detection Not Implemented |0| Placeholder |\n|  | 0102 | Dynamic Analysis Tools Detection Not Implemented |0| Placeholder |\n|  | 0103 | RASP Techniques Not Implemented |0| Placeholder |\n|  | 0104 | App Integrity Not Verified |0| Placeholder |\n|  | 0105 | Integrity of App Resources Not Verified |0| Placeholder |\n|  | 0106 | Official Store Verification Not Implemented |0| Placeholder |\n|  | 0107 | Runtime Code Integrity Not Verified |0| Placeholder |\n| PRIVACY |  |  |  |  |\n|  | 0108 | Sensitive Data in Network Traffic |0| Beta |\n|  | 0109 | Lack of Anonymization or Pseudonymisation Measures |0| Beta |\n|  | 0110 |  Use of Unique Identifiers for User Tracking |0| Beta |\n|  | 0111 | Inadequate Privacy Policy |0| Beta |\n|  | 0112 | Inadequate Data Collection Declarations |0| Beta |\n|  | 0113 | Lack of Proper Data Management Controls |0| Beta |\n|  | 0114 | Inadequate Data Visibility Controls |0| Beta |\n|  | 0115 | Inadequate or Ambiguous User Consent Mechanisms |0| Beta |\n|  | 0117 | Inadequate Permission Management |0| Beta |'

In [48]:
# Split data into seperate rows
specific_data_rows = uncleaned_coverage_data.split("\n")

# Store data in a csv file, using the "|" as seperators
with open("../data/own_coverage_data_uncleaned.csv", "w", newline="", encoding='UTF-8') as file:
    writer = csv.writer(file)
    for row in specific_data_rows:
        # Split rows on "|" and write them to the csv file
        writer.writerow(row.split("|"))

In [49]:
# Convert it to a pandas dataframe
coverage_data_df = pd.read_csv("../data/own_coverage_data_uncleaned.csv")

# Drop first and last columns
coverage_data_df.drop(["Unnamed: 0", "Unnamed: 6"], axis=1, inplace=True)
# Drop first row
coverage_data_df.drop(0, inplace=True)

# Strip column names of whitespaces
coverage_data_df = strip_df_whitespaces(coverage_data_df)

# Add uniform missing values sign
for column in coverage_data_df.columns:
    coverage_data_df.loc[coverage_data_df[column] == "", column] = "-"

# Reset the index to a meaningful one, considering the now removed values
coverage_data_df.reset_index(drop=True, inplace=True)

# Drop missing values
coverage_data_df.dropna(inplace=True)

display(coverage_data_df)

,Category,#,Description,Implementation-Status,MAS-Status
0,STORAGE,-,-,-,-
1,-,0001,Insertion of Sensitive Data into Logs,1,Beta
2,-,0002,Sensitive Data Stored With Insufficient Access...,1,Placeholder
3,-,0003,Backup Unencrypted,1,Placeholder
4,-,0004,Sensitive Data Not Excluded From Backup,1,Beta
...,...,...,...,...,...
120,-,0112,Inadequate Data Collection Declarations,0,Beta
121,-,0113,Lack of Proper Data Management Controls,0,Beta
122,-,0114,Inadequate Data Visibility Controls,0,Beta
123,-,0115,Inadequate or Ambiguous User Consent Mechanisms,0,Beta
124,-,0117,Inadequate Permission Management,0,Beta

In [50]:
# Add correct "App Name" value to every row
app_names = coverage_data_df.loc[coverage_data_df["Category"] != "-", "Category"].values
app_names_indexes = []
for app_name in app_names:
    app_names_indexes.append(coverage_data_df[coverage_data_df["Category"] == app_name].index[0])
# Add last index of dataframe rows as guardian value for next operation
app_names_indexes.append(len(coverage_data_df.values))


# Go through all app name indexes, locate the rows which require the same app name and fill them in
for index in range(len(app_names_indexes)-1):
    coverage_data_df.iloc[app_names_indexes[index]:app_names_indexes[index+1], 0] = app_names[index]

# Remove rows which only hold the category title and no actual vulnerability (8 of them in total)

# Drop non vulnerability rows
coverage_data_df.drop(coverage_data_df.loc[coverage_data_df["Description"] == "-"].index, inplace=True)

# Count amount of "-" missing values
print(np.sum(coverage_data_df["Description"] == "-"))

# Reset the index to a meaningful one, considering the now removed values
coverage_data_df.reset_index(drop=True, inplace=True)
display(coverage_data_df)

0

,Category,#,Description,Implementation-Status,MAS-Status
0,STORAGE,0001,Insertion of Sensitive Data into Logs,1,Beta
1,STORAGE,0002,Sensitive Data Stored With Insufficient Access...,1,Placeholder
2,STORAGE,0003,Backup Unencrypted,1,Placeholder
3,STORAGE,0004,Sensitive Data Not Excluded From Backup,1,Beta
4,STORAGE,0006,Sensitive Data Stored Unencrypted in Private S...,1,Beta
...,...,...,...,...,...
112,PRIVACY,0112,Inadequate Data Collection Declarations,0,Beta
113,PRIVACY,0113,Lack of Proper Data Management Controls,0,Beta
114,PRIVACY,0114,Inadequate Data Visibility Controls,0,Beta
115,PRIVACY,0115,Inadequate or Ambiguous User Consent Mechanisms,0,Beta
116,PRIVACY,0117,Inadequate Permission Management,0,Beta

In [51]:
#Extract the only necessary column, as to compare it to the one in specific_data_cleaned.csv
coverage_data_df["Vulnerability"] = "MASWE-" + coverage_data_df["#"] + ": " + coverage_data_df["Description"]

# Drop all unimplemented vulnerabilities
coverage_data_df = coverage_data_df[coverage_data_df["Implementation-Status"] == "1"]

# Drop all other columns
#coverage_data_df.drop(coverage_data_df.columns[1:-1], axis=1, inplace=True)
coverage_data_df = coverage_data_df[["Category", "Vulnerability"]]

# Reset the index to a meaningful one, considering the now removed values
coverage_data_df.reset_index(drop=True, inplace=True)
display(coverage_data_df)

    Category                                      Vulnerability
0    STORAGE  MASWE-0001: Insertion of Sensitive Data into Logs
1    STORAGE  MASWE-0002: Sensitive Data Stored With Insuffi...
2    STORAGE                     MASWE-0003: Backup Unencrypted
3    STORAGE  MASWE-0004: Sensitive Data Not Excluded From B...
4    STORAGE  MASWE-0006: Sensitive Data Stored Unencrypted ...
5    STORAGE  MASWE-0007: Sensitive Data Stored Unencrypted ...
6     CRYPTO  MASWE-0009: Improper Cryptographic Key Generation
7     CRYPTO  MASWE-0010: Improper Cryptographic Key Derivation
8     CRYPTO  MASWE-0011: Cryptographic Key Rotation Not Imp...
9     CRYPTO  MASWE-0012: Insecure or Wrong Usage of Cryptog...
10    CRYPTO  MASWE-0014: Cryptographic Keys Not Properly Pr...
11    CRYPTO  MASWE-0015: Deprecated Android KeyStore Implem...
12    CRYPTO  MASWE-0016: Unsafe Handling of Imported Crypto...
13    CRYPTO  MASWE-0017: Cryptographic Keys Not Properly Pr...
14    CRYPTO  MASWE-0018: Cryptographic Keys Access Not Rest...
15    CRYPTO     MASWE-0019: Risky Cryptography Implementations
16    CRYPTO                    MASWE-0020: Improper Encryption
17    CRYPTO                       MASWE-0021: Improper Hashing
18    CRYPTO  MASWE-0022: Predictable Initialization Vectors...
19    CRYPTO                          MASWE-0023: Risky Padding
20    CRYPTO  MASWE-0024: Improper Use of Message Authentica...
21    CRYPTO  MASWE-0025: Improper Generation of Cryptograph...
22    CRYPTO  MASWE-0026: Improper Verification of Cryptogra...
23    CRYPTO      MASWE-0027: Improper Random Number Generation
24  PLATFORM  MASWE-0053: Sensitive Data Leaked via the User...
25  PLATFORM  MASWE-0055: Sensitive Data Leaked via Screenshots
26  PLATFORM             MASWE-0064: Insecure Content Providers
27  PLATFORM           MASWE-0067: Debuggable Flag Not Disabled

In [52]:
# Export cleaned df to csv
coverage_data_df.to_csv("../data/own_coverage_data_cleaned.csv", index=False)